### ISSUE TITLE
Vectorization process

### ISSUE THREAD

**Issue by TheodoreGalanos** [3dlg-hcvc/plan2scene#21]
Hello! Thank you for sharing your work, incredible!

I am curious if you could help me understand where the vectorization happens in the code and whether this is on top of a top down image of the layout or an actual cad file.

Thanks!

**Comment by madhawav** [comment]
Hi @TheodoreGalanos. Thank you for your interest.

The Rent3D++ dataset we use provides us with the floorplan vector. It is in a format called scene.json which we parse using the [code here](https://github.com/3dlg-hcvc/plan2scene/blob/main/code/src/arch_parser/parser.py). So the vectorization process is not a part of this code repository. We assume a vectorized floorplan is given.

On a related note, in the past, I have used [this project](http://art-programmer.github.io/floorplan-transformation/paper.pdf) for floorplan vectorization.

**Comment by TheodoreGalanos** [comment]
Hi @madhawav ,

Thanks that makes sense, just wanted a sanity check :) Thank you for the reference, I have tried that one before but I felt it was too hard coded to its data. I'll give it another shot.
