### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by ak9250** [3dlg-hcvc/plan2scene#22]
Hi, great work, can you please add a google colab for inference?

**Comment by madhawav** [comment]
Hi @ak9250 
This is definitely a great idea. I will look into it. 
Thanks

**Comment by madhawav** [comment]
I have prepared a [Colab Notebook](https://colab.research.google.com/drive/1lDkbfIV0drR1o9D0WYzoWeRskB91nXHq?usp=sharing). Will do some more final touches and link to the README.MD file.

**Comment by ak9250** [comment]
@madhawav looks good thanks
