### ISSUE TITLE
Pre-trained model (weights) link is broken?

### ISSUE THREAD

**Issue by Casyfill** [3dlg-hcvc/plan2scene#26]
Hi guys! It seems that the trained model link is broken, do you mind updating it?
Hoped to use your model for the hackathon (don't need to be a SOTA best model but something would be very handy).

Also, I might have missed it, but how long/hard is it to train your model, and what hardware do you use?
Thank you in advance!

**Comment by madhawav** [comment]
Hi @Casyfill,
Both pre-trained model weight links seem to work for me. Can you check again? 
We used a 2080ti 11GB to train but it may support GPUS with less memory also. Inference would probably take 4 - 6GB ram.

**Comment by Casyfill** [comment]
Thanks! I meant the third (last) one.

**Comment by madhawav** [comment]
It seems Google Chrome blocks downloads since those links are not https links. Can you try using a different browser? 
The linux command wget also works:
wget http://aspis.cmpt.sfu.ca/projects/plan2scene/pretrained-models/substance-classifier/v2/checkpoints/correct_57_total_64_epoch_120.ckpt

**Comment by madhawav** [comment]
Hi @Casyfill 
I updated weight links to HTTPS now. Those seem to work fine with Google Chrome. Please confirm.

**Comment by Casyfill** [comment]
Thanks, that's awesome! Btw same issue  and same solution for data links sent via email.

**Comment by madhawav** [comment]
Thanks @Casyfill.

**Comment by costacis21** [comment]
i know this is a closed issue, but i've requested the model a couple of times over the past 2 months since it's a locked gdrive link. I had no response. can anyone help on this matter?
