### ISSUE TITLE
Side Issue - SSTK Docker?

### ISSUE THREAD

**Issue by Casyfill** [3dlg-hcvc/plan2scene#27]
It's obviously beyond this work/repo responsibility, but I had such a great experience with your colab notebook - unless I got the result and tried to view it using smart scene toolkit - and it is hard to install and the existing Dockerfile fails to compile. Can you share your docker image, by any chance>

**Comment by madhawav** [comment]
Hi @Casyfill 
I've never used the docker file with smart scene toolkit. But, the instructions for directly installing it on the host machine works fine. Can you try that approach?

**Comment by Casyfill** [comment]
Thanks for the quick response. I tried and `.build.sh` fails for me
```
2609 verbose stack Error: command failed
2609 verbose stack     at ChildProcess.<anonymous> (/Users/philippk/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
2609 verbose stack     at ChildProcess.emit (node:events:394:28)
2609 verbose stack     at maybeClose (node:internal/child_process:1067:16)
2609 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2610 verbose pkgid sstk@0.6.1
2611 verbose cwd /Users/philippk/Dropbox/se_projects/July21_Hackweek/FloorPlanner/sstk
2612 verbose Darwin 20.5.0
2613 verbose argv "/Users/philippk/.nvm/versions/node/v16.5.0/bin/node" "/Users/philippk/.nvm/versions/node/v16.5.0/bin/npm" "install"
2614 verbose node v16.5.0
2615 verbose npm  v7.19.1
2616 error code 1
2617 error path /Users/philippk/Dropbox/se_projects/July21_Hackweek/FloorPlanner/sstk
2618 error command failed
2619 error command sh -c node getdata.js && npm run bootstrap
2620 verbose exit 1

```

**Comment by madhawav** [comment]
I see. Looking at above, it seems the node version you use (16.5.0) is different.  The SSTK instructions suggest to use 10.23.2. Refer to the following step by SSTK

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
source ~/.bashrc 
nvm install v10.23.2
```

**Comment by Casyfill** [comment]
Thanks!
I tried that and still have troubles with many packages, dependence on obsolete py27, etc. I will try to solve it but for now I made `plan2scene` run, but have no way to see/valuate the outcome since I can't make sstk to work :sad:. Would be awesome to build some dockerized versions for all those awesome tools in the future!

**Comment by madhawav** [comment]
Hi @Casyfill 
Can I know which OS you are using?

I tested at my end using a Ubuntu 20.04 machine with a __Python 3.8__ conda environment. The SSTK installation works fine.

Here are the exact commands I used.
```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
source ~/.bashrc
nvm install v10.23.2

git clone https://github.com/smartscenes/sstk.git

cd sstk
./build.sh
cd server
./run.sh
```

**Comment by madhawav** [comment]
Hi @Casyfill 
The following commands should work if you are using docker. Here, I have directly used an Ubuntu 20.04 image instead of writing a docker file.  

I tested the following using my local docker.

```bash
docker run -it -p 8010:8010 ubuntu:20.04 

apt-get update
apt-get install -y git curl
apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev libvips

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
source ~/.bashrc
nvm install v10.23.2

git clone https://github.com/smartscenes/sstk.git
cd sstk
./build.sh
cd server
./run.sh
```

**Comment by Casyfill** [comment]
THanks! That did work (finally!)

But I can't make it to show anything aside from initial buttons, and
nothing happens when I upload a scene.json from Plan2Scene :-(

>

**Comment by madhawav** [comment]
Hi @Casyfill 

I managed to get things running in docker by running the following sequence of commands.

```bash
docker run -it -p 8010:8010 ubuntu:16.04
apt-get update
apt-get install -y curl git build-essential libxi-dev libglu1-mesa-dev libglew-dev libvips
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
source ~/.bashrc
nvm install v10.23.2

git clone https://github.com/smartscenes/sstk.git
cd sstk
./build.sh
node getdata.js
cd client
npm install
npm run build
cd ../server
./run.sh
```

Access http://localhost:8010/scene-viewer.html

I tested the above in https://labs.play-with-docker.com/ and it works. So, I assume it will work in your docker as well. 

If the above doesn't work, please send me a copy of the errors printed in the developer console of the browser.

**Comment by Casyfill** [comment]
Thanks, This finally made it work! Thank you so much!
Thanks for all your help and the project itself, btw!

I am working for StreetEasy, it's Zillow's NYC brand - we have tons of
floorplans and photos, and I hope to try to digitize them into 3d.
Your work looks very promising and useful for that. I am just on internal
hackathon right now, but theoretically, we could share a dataset if that
would be useful for your research in the future.

**Comment by Casyfill** [comment]
(and Zillow at large works on 3d scanning / capture as well) :-)

**Comment by madhawav** [comment]
All the best @Casyfill. Happy to discuss further. How can we stay in touch? 
My LinkedIn: https://www.linkedin.com/in/madhawav/
