### ISSUE TITLE
Rent3D dataset no longer available

### ISSUE THREAD

**Issue by dfraska-ftl** [3dlg-hcvc/plan2scene#33]
While I was able to download the Rent3D++ dataset, the original Rent3D dataset link at http://www.cs.toronto.edu/~fidler/projects/rent3D.html seems to be broken. If my understanding is correct, that data would be necessary to retrain this model. Does anyone have an alternative download link?

I've already e-mailed the Rent3D researchers through their e-mail links on that page and if I get a response I'll update this issue with a new link.

**Comment by madhawav** [comment]
Hi, 

Thank you for your interest.  

For training the model, the Rent3D dataset is not required. 

For training the texture synthesis stage, you can use the stationary textures v2 dataset as described here: https://github.com/3dlg-hcvc/plan2scene/blob/main/docs/md/stationary_textures_dataset_v2.md 

For texture propagation stage, you can use the rectified surface crops provided with the Rent3D++ dataset.

**Comment by dfraska-ftl** [comment]
Ok, great thanks for the reply.
